### PR TITLE
Add ldap-backend and pdns-recursor

### PR DESCRIPTION
**Pull request by kronos-pbrideau**
Following the example of other backend in this module, here is a new backend for ldap

Also, add pdns-recursor
The configs is done with a template, because the recursor does not use the conf.d configurations...
If configs not listed in this module should be used, the template would need to get modified.  It is not ideal, but it works for now.

### CODE REVIEW

**Comment by antonlindstrom** [comment]
Looks good! Do you mind adding a bit of description in this PR describing what you did?

Thanks!

**Comment by kronos-pbrideau** [comment]
Maybe we could use pnds-recursor::config and use hiera to change directly the config file instead of using template? As in [camptocamp-postfix] (https://github.com/camptocamp/puppet-postfix/blob/master/manifests/config.pp)

It could look like:
pdns::recursor::config { 'allowed-from' : value => '127.0.0.0/8, 10.0.0.0/8' }

Any though ?

**Comment by kronos-pbrideau** [comment]
hmmm, nevermind... it would probably require a new lens for hiera...  Guess I will change the template to add the options I want.

**Comment by antonlindstrom** [comment]
@kronos-pbrideau Perfect, thank you so much for contributing! Do you mind squashing the typo commit?

Thanks!

**Comment by kronos-pbrideau** [comment]
Here it is, squashed!  I thought about doing it at first, but i'm always afraid when doing `git push --force`.  Glad you asked me to do it, allowing me to be (a little) less worried about it!

**Comment by kronos-pbrideau** [comment]
I though adding the 'relative' option would make the 'ERROR: [...] not in autoload module layout [...]' lines disapear
Tested locally, when running `puppet-lint --relative --no-80chars-check --no-class_inherits_from_params_class-check` worked without errors.  I guess I should dive deeper into this rake stuff instead of just trying blindly.

**Comment by antonlindstrom** [comment]
@kronos-pbrideau Perfect, thanks!

I think there are some issues with the versions in Travis, I think I have to dive into that to solve it later.

**Pull request merged**
